# Generated by Django 5.1.2 on 2025-01-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('solaire', 'Énergie Solaire'), ('reparation', 'Réparation / Maintenance'), ('antiIncendie', 'Équipements Anti-Incendie'), ('securiteElectronique', 'Sécurité Électronique'), ('jeuxVideo', 'Consoles de Jeux'), ('electricite', 'Électricité'), ('evaluationEnvironnementale', 'Évaluation Environnementale')], max_length=50, verbose_name='Service')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('type_batiment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de bâtiment')),
                ('nombre_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces')),
                ('modele_machine', models.CharField(blank=True, max_length=120, null=True, verbose_name='Modèle de la machine')),
                ('fabricant', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fabricant')),
                ('diagnostic_client', models.TextField(blank=True, null=True, verbose_name='Auto-diagnostic du client')),
            ],
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'appareil")),
                ('puissance', models.PositiveIntegerField(verbose_name='Puissance (W)')),
                ('duree', models.PositiveIntegerField(verbose_name='Durée (h/jour)')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to='wefix.devis')),
            ],
        ),
    ]
