# Generated by Django 5.1.2 on 2025-01-27 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='date_demande',
        ),
        migrations.AddField(
            model_name='devis',
            name='appareils',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 27, 21, 54, 21, 435511, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='diagnostic_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='fabricant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='modele_machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.CharField(choices=[('solaire', 'Énergie Solaire'), ('reparation', 'Réparation/Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_batiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Appareil',
        ),
    ]
