# Generated by Django 5.1.2 on 2025-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefix', '0002_remove_devis_date_demande_devis_appareils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='appareils',
            field=models.JSONField(blank=True, default=list, verbose_name='Appareils'),
        ),
    ]
