# Generated by Django 5.1.5 on 2025-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefix', '0003_alter_devis_appareils'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='accessoires',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='equipements_souhaites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devis',
            name='modele_console',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='nombre_points_acces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='probleme_console',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='services_souhaites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devis',
            name='superficie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='symptomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_console',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_etablissement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='appareils',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.CharField(choices=[('solaire', 'Énergie Solaire'), ('reparation', 'Réparation/Maintenance'), ('antiIncendie', 'Équipements Anti-Incendie'), ('securiteElectronique', 'Sécurité Électronique'), ('jeuxVideo', 'Consoles de Jeux'), ('electricite', 'Électricité'), ('evaluationEnvironnementale', 'Évaluation Environnementale')], max_length=50),
        ),
    ]
